[project]
name = "pca533-octrees"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pybind11>=3.0.1",
]

[dependency-groups]
dev = [
    "pybind11>=3.0.1",
]
